# Exercise: Use sqlalchemy, PostgresQL, Pandas to interact with the table `tblnorthwind` 

## Objective

Create a python program which uses sqlalchemy module to interact with PostgresQL db and perform various analysis.

## Instructions

### 1. Install required library.

   ```bash
   # in terminal
   python -m venv .dbenv
   . .dbenv/bin/activate
   pip install -r requirements.txt
   ```

### 2. Connect to training database used in week 2 weekly project and check version of the PostgresQL.

In [3]:
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, insert, select, text

engine = create_engine(
    'postgresql://markus:1markus!@localhost:5432/training'
)

In [4]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT version();"))  # PostgreSQL version
    version = result.fetchone()
    print("[INFO] PostgreSQL version:", version[0])

[INFO] PostgreSQL version: PostgreSQL 16.13 (Ubuntu 16.13-1.pgdg24.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit

### 3. Count total number of records from the table tblnorthwind.

In [21]:
with engine.connect() as conn:
    stmt = text("SELECT COUNT(*) FROM northwind.tblnorthwind")
    print(stmt)
    result = conn.execute(stmt)
    for r in result:
        print(r)

SELECT COUNT(*) FROM northwind.tblnorthwind
(1000,)

### 4. Create user table and display inserted records. User table's ddl is provided in theory part.

In [27]:
metadata = MetaData(schema="northwind")
users = Table(
    "users", metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String),
    Column("email", String)
)
metadata.create_all(engine)

In [28]:
with engine.connect() as conn:
    for stmt in (
        insert(users).values(name="Markus", email="markus@example.com"),
        insert(users).values(name="Phillippe", email="phillippe@example.com"),
        insert(users).values(name="Sinyoung", email="sinyoung@example.com"),
    ):
        print(stmt)
        conn.execute(stmt)
        conn.commit()

    stmt = text("SELECT * FROM users")
    result = conn.execute(stmt)
    for r in result:
        print(r)

INSERT INTO northwind.users (name, email) VALUES (:name, :email)
INSERT INTO northwind.users (name, email) VALUES (:name, :email)
INSERT INTO northwind.users (name, email) VALUES (:name, :email)
(1, 'Markus', 'markus@example.com')
(2, 'Phillippe', 'phillippe@example.com')
(3, 'Sinyoung', 'sinyoung@example.com')

### 5. Execute: Full ORM Workflow by pointing to tblnorthwind table. (Optional)

### 6. Store tblnorthwind table content in pandas dataframe and perform below operations:
   - Find the total number of orders placed by each customer.
   - Calculate the total revenue (unitprice × quantity) for each product.
   - Find the average discount given per category.
   - Identify the employees who have handled more than 50 orders.
   - List all orders where the shipped date is later than the required date.

In [30]:
import pandas as pd
with engine.connect() as conn:
    stmt = text("SELECT * FROM tblnorthwind")
    result = conn.execute(stmt)
    df = pd.DataFrame(result.fetchall(), columns=result.keys())

In [36]:
#print(df.head())
#print(df.info())

In [37]:
df.columns

Index(['orderid', 'customerid', 'employeeid', 'orderdate', 'requireddate',
       'shippeddate', 'shipvia', 'freight', 'productid', 'unitprice',
       'quantity', 'discount', 'companyname', 'contactname', 'contacttitle',
       'lastname', 'firstname', 'title', 'productname', 'supplierid',
       'categoryid', 'quantityperunit', 'unitprice_1', 'unitsinstock',
       'unitsonorder', 'reorderlevel', 'discontinued', 'categoryname',
       'suppliercompanyname', 'suppliercontactname', 'suppliercontacttitle'],
      dtype='object')

In [62]:
df.groupby(["customerid", "orderid"]).agg({"productid": "count"}).head(50)  #.count()

                    productid
customerid orderid
ANATR      10308            2
           10625            3
ANTON      10365            1
           10507            2
           10535            4
           10573            3
AROUT      10355            2
           10383            3
           10453            2
           10558            5
BERGS      10278            4
           10280            3
           10384            2
           10444            4
           10445            2
           10524            4
           10572            4
BLAUS      10501            1
           10509            1
           10582            2
           10614            3
BLONP      10265            2
           10297            2
           10360            5
           10436            4
           10449            3
           10559            2
           10566            3
           10584            1
BOLID      10326            3
BONAP      10331            1
           10340            3
           10362            3
           10470            3
           10511            3
           10525            2
BOTTM      10389            4
           10410            2
           10411            3
           10431            3
           10492            2
BSBEV      10289            2
           10471            2
           10484            3
           10538            2
           10539            4
           10578            2
           10599            1
CACTU      10521            3
CENTC      10259            2

In [50]:
df[["customerid", "orderid"]].sort_values("customerid")

    customerid  orderid
999      ANATR    10625
997      ANATR    10625
161      ANATR    10308
162      ANATR    10308
998      ANATR    10625
..         ...      ...
337      WOLZA    10374
336      WOLZA    10374
959      WOLZA    10611
958      WOLZA    10611
957      WOLZA    10611

[1000 rows x 2 columns]

In [48]:
df.groupby("customerid")["orderid"].nunique()

customerid
ANATR     2
ANTON     4
AROUT     4
BERGS     7
BLAUS     4
         ..
WARTH    11
WELLI     3
WHITC     6
WILMK     1
WOLZA     2
Name: orderid, Length: 85, dtype: int64

In [41]:
df.groupby("productid").apply(lambda x: x["unitprice"] * x["quantity"]).sum()

/tmp/ipykernel_133748/3280125590.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("productid").apply(lambda x: x["unitprice"] * x["quantity"]).sum()

Decimal('589935.66')


### 7. Create customers table which was created in week 2 project.