# Final Exercise on pandas

We'll be working with the `wine` datasets that are located in the `data` folder in this day's directory.

## Task 1.

Read the `winequality-red.csv` data into a `DataFrame`, and the `winequality-white.csv` into another `DataFrame`.

In [1]:
import pandas as pd

In [2]:
redwine_df = pd.read_csv('data/winequality-red.csv', delimiter=';')
redwine_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
whitewine_df = pd.read_csv('data/winequality-white.csv', delimiter=';')
whitewine_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [4]:
dfr = redwine_df.copy()
dfw = whitewine_df.copy()
dfr['type'] = 'red'
dfw['type'] = 'white'
wine_df = pd.concat([dfr, dfw], ignore_index=True)
wine_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white

## Task 2.

 Double check that you've read them in right by using some of the attributes and methods available on `DataFrames` for getting a general sense of your data.

In [75]:
redwine_df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [76]:
whitewine_df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000
mean,6.854788,0.278241,0.334192,6.391415,0.045772,35.308085,138.360657,0.994027,3.188267,0.489847,10.514267,5.877909
std,0.843868,0.100795,0.121020,5.072058,0.021848,17.007137,42.498065,0.002991,0.151001,0.114126,1.230621,0.885639
min,3.800000,0.080000,0.000000,0.600000,0.009000,2.000000,9.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.300000,0.210000,0.270000,1.700000,0.036000,23.000000,108.000000,0.991723,3.090000,0.410000,9.500000,5.000000
50%,6.800000,0.260000,0.320000,5.200000,0.043000,34.000000,134.000000,0.993740,3.180000,0.470000,10.400000,6.000000
75%,7.300000,0.320000,0.390000,9.900000,0.050000,46.000000,167.000000,0.996100,3.280000,0.550000,11.400000,6.000000
max,14.200000,1.100000,1.660000,65.800000,0.346000,289.000000,440.000000,1.038980,3.820000,1.080000,14.200000,9.000000

In [5]:
redwine_df.info(), whitewine_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 459.3 KB

(None, None)

In [6]:
redwine_df.describe()['alcohol'], whitewine_df.describe()['alcohol']

(count    1599.000000
 mean       10.422983
 std         1.065668
 min         8.400000
 25%         9.500000
 50%        10.200000
 75%        11.100000
 max        14.900000
 Name: alcohol, dtype: float64,
 count    4898.000000
 mean       10.514267
 std         1.230621
 min         8.000000
 25%         9.500000
 50%        10.400000
 75%        11.400000
 max        14.200000
 Name: alcohol, dtype: float64)

## Task 3.

I've decided that this month I want to stay away from wines with relatively high alcohol content. To do that, I'm going to avoid any wines that have a greater alcohol content than the mean alcohol content, and you're going to help me do this. To achieve this, let's do the following: 

  * Find the mean alcohol content, separately, for reds and whites.  
  * Create a `Series` that holds whether each row in each `DataFrame` (the reds, and whites) has a higher alcohol content than the mean. 
  * Merge this `Series` onto the `DataFrame`. I can imagine doing this with either a `.join()` or using `pd.concat()`. For practice, do it with both. Note: merges with `Series` work the same way that they work with `DataFrames`.  
  * Return back to me all those rows that will help me stay away from those wines with a higher alcohol content.

In [7]:
wine_df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'type'],
      dtype='object')

In [8]:
wine_df.groupby('type').mean()['alcohol']

type
red      10.422983
white    10.514267
Name: alcohol, dtype: float64

In [9]:
red_mean_alc = redwine_df['alcohol'].mean()
white_mean_alc = whitewine_df['alcohol'].mean()
red_mean_alc

np.float64(10.422983114446529)

In [10]:
red_alc_above_avg = (redwine_df['alcohol'] > red_mean_alc).rename('alcohol_above_avg')
white_alc_above_avg = (whitewine_df['alcohol'] > white_mean_alc).rename('alcohol_above_avg')
red_alc_above_avg

0       False
1       False
2       False
3       False
4       False
        ...
1594     True
1595     True
1596     True
1597    False
1598     True
Name: alcohol_above_avg, Length: 1599, dtype: bool

In [11]:
pd.concat([redwine_df, red_alc_above_avg], axis=1)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alcohol_above_avg
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,False
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,False
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,False
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,False
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,True
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,True
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,True
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,False
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,True

In [12]:
redwine_df = redwine_df.join(red_alc_above_avg)
whitewine_df = whitewine_df.join(white_alc_above_avg)
redwine_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alcohol_above_avg
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,False
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,False
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,False
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,False
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,True
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,True
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,True
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,False
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,True

In [17]:
redwine_df.describe()["alcohol"][["min","mean","max"]]

min      8.400000
mean    10.422983
max     14.900000
Name: alcohol, dtype: float64

In [19]:
redwine_df[redwine_df['alcohol_above_avg'] == False]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alcohol_above_avg
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,False
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,False
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,False
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,False
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1572,7.3,0.690,0.32,2.2,0.069,35.0,104.0,0.99632,3.33,0.51,9.5,5,False
1583,6.2,0.460,0.29,2.1,0.074,32.0,98.0,0.99578,3.33,0.62,9.8,5,False
1589,6.6,0.725,0.20,7.8,0.073,29.0,79.0,0.99770,3.29,0.54,9.2,5,False
1593,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,False
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,False

In [20]:
whitewine_df[whitewine_df['alcohol_above_avg'] == False]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alcohol_above_avg
0,7.0,0.270,0.36,20.70,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6,False
1,6.3,0.300,0.34,1.60,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6,False
2,8.1,0.280,0.40,6.90,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6,False
3,7.2,0.230,0.32,8.50,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,False
4,7.2,0.230,0.32,8.50,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4888,6.8,0.220,0.36,1.20,0.052,38.0,127.0,0.99330,3.04,0.54,9.2,5,False
4889,4.9,0.235,0.27,11.75,0.030,34.0,118.0,0.99540,3.07,0.50,9.4,6,False
4892,6.5,0.230,0.38,1.30,0.032,29.0,112.0,0.99298,3.29,0.54,9.7,5,False
4894,6.6,0.320,0.36,8.00,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,False
4895,6.5,0.240,0.19,1.20,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,False

## Task 4. 

Let's say that I want to get started on cutting back next month. This time, though, I want to focus on staying away from those wines with a high acidity. Specifically, I want to stay away from those wines that are in the highest bin of fixed acidity (highest bin out of 5). You're now going to help me do this. To achieve this, let's do the following: 

 * Separate the rows in each `DataFrame` into 5 equal width bins (not equal to quintiles) based off their fixed acidity. 
 * Merge the resulting `Series` holding these 5 bins onto the original `DataFrame`. I can imagine also doing this with either `.join()` or using `pd.concat()`. Try doing it with both for practice. 
 * Return back to me all those rows that are **not in** the top bin in terms of fixed acidity.

In [21]:
whitewine_df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'alcohol_above_avg'],
      dtype='object')

In [62]:
whitewine_df['fixed_acidity_bins'] = pd.cut(whitewine_df['fixed acidity'], bins=5, 
                                             labels=['Very Low', 'Low', 'Medium', 'High', 'Very High'])
whitewine_df['fixed_acidity_bins'].unique()

['Low', 'Medium', 'Very Low', 'High', 'Very High']
Categories (5, object): ['Very Low' < 'Low' < 'Medium' < 'High' < 'Very High']

In [72]:
whitewine_df.groupby(['fixed_acidity_bins'])

/tmp/ipykernel_239530/3045294099.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  whitewine_df.groupby(['fixed_acidity_bins'])

In [74]:
whitewine_df.groupby(
    ['fixed_acidity_bins'], 
    observed=False  # we also want to see results for empty bins if the exist, give explicitely to silence warning
).describe()

                   fixed acidity                                               \
                           count       mean       std   min   25%   50%   75%
fixed_acidity_bins
Very Low                   471.0   5.494904  0.336021   3.8   5.3   5.6   5.8
Low                       3953.0   6.816506  0.519229   5.9   6.4   6.8   7.2
Medium                     467.0   8.485653  0.478943   8.0   8.1   8.3   8.7
High                         6.0  10.666667  0.595539  10.2  10.3  10.5  10.7
Very High                    1.0  14.200000       NaN  14.2  14.2  14.2  14.2

                         volatile acidity            ... alcohol         \
                     max            count      mean  ...     75%    max
fixed_acidity_bins                                   ...
Very Low             5.8            471.0  0.287919  ...    12.1  14.05
Low                  7.9           3953.0  0.276555  ...    11.3  14.20
Medium              10.0            467.0  0.283073  ...    11.2  13.30
High                11.8              6.0  0.255000  ...     9.7   9.90
Very High           14.2              1.0  0.270000  ...    11.1  11.10

                   quality
                     count      mean       std  min   25%  50%   75%  max
fixed_acidity_bins
Very Low             471.0  6.072187  0.922007  3.0  5.00  6.0  7.00  8.0
Low                 3953.0  5.883380  0.870868  3.0  5.00  6.0  6.00  9.0
Medium               467.0  5.653105  0.905163  3.0  5.00  6.0  6.00  9.0
High                   6.0  4.500000  1.378405  3.0  3.25  4.5  5.75  6.0
Very High              1.0  6.000000       NaN  6.0  6.00  6.0  6.00  6.0

[5 rows x 96 columns]

In [94]:
redwine_df['fixed_acidity_bins'] = pd.cut(redwine_df['fixed acidity'], bins=5, 
                                          labels=['Very Low', 'Low', 'Medium', 'High', 'Very High'])
redwine_df.groupby(
    ['fixed_acidity_bins'], 
    observed=False  # we also want to see results for empty bins if the exist, give explicitely to silence warning
).describe()

                   fixed acidity                                          \
                           count       mean       std   min    25%   50%
fixed_acidity_bins
Very Low                   274.0   6.271898  0.511099   4.6   6.00   6.4
Low                        913.0   7.850493  0.641204   6.9   7.30   7.8
Medium                     298.0  10.069128  0.573124   9.2   9.60  10.0
High                       102.0  12.146078  0.572760  11.4  11.60  12.0
Very High                   12.0  14.800000  0.845308  13.7  13.95  15.0

                                 volatile acidity            ... alcohol  \
                       75%   max            count      mean  ...     75%
fixed_acidity_bins                                           ...
Very Low             6.700   6.8            274.0  0.579489  ...  11.700
Low                  8.300   9.1            913.0  0.544392  ...  10.900
Medium              10.500  11.3            298.0  0.466275  ...  11.200
High                12.575  13.5            102.0  0.429265  ...  10.900
Very High           15.525  15.9             12.0  0.453333  ...  11.125

                         quality
                     max   count      mean       std  min  25%  50%   75%  max
fixed_acidity_bins
Very Low            14.0   274.0  5.609489  0.819218  3.0  5.0  6.0  6.00  8.0
Low                 14.0   913.0  5.562979  0.774192  3.0  5.0  5.0  6.00  8.0
Medium              13.4   298.0  5.791946  0.851026  3.0  5.0  6.0  6.00  8.0
High                13.3   102.0  5.872549  0.840457  3.0  5.0  6.0  6.00  8.0
Very High           14.9    12.0  5.916667  0.792961  5.0  5.0  6.0  6.25  7.0

[5 rows x 96 columns]

---

## side quest: 

In Pandas there is a deprecation warning on groupby with categorical data and implicit observed=False (default),
 observed=True will be the new default in Pandas 3

In [ ]:
# see notes in release notes for pandas 3.0.0 https://pandas.pydata.org/pandas-docs/stable/whatsnew/v3.0.0.html#improved-behavior-in-groupby-for-observed-false

df = pd.DataFrame(
    {
        "key1": pd.Categorical(list("aabb"), categories=list("abc")),
        "key2": [1, 1, 1, 2],
        "values": [1, 2, 3, 4],
    }
)
df

  key1  key2  values
0    a     1       1
1    a     1       2
2    b     1       3
3    b     2       4

In [ ]:
gb = df.groupby("key1", observed=False)  # include also not observed categories, in this case 'c'
gb[["values"]].apply(lambda x: x.sum())

      values
key1
a          3
b          7
c          0

In [ ]:
gb = df.groupby("key1", observed=True)  # only include observed categories, in this case 'a' and 'b', 'c' is not included in the result
gb[["values"]].apply(lambda x: x.sum())

      values
key1
a          3
b          7

## End of side quest 

---

In [97]:
redwine_df[~(redwine_df['fixed_acidity_bins'] == 'Very High')]  #['fixed_acidity_bins'].unique()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alcohol_above_avg,fixed_acidity_bins
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,False,Low
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,False,Low
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,False,Low
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,False,Medium
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,False,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,True,Very Low
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,True,Very Low
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,True,Very Low
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,False,Very Low
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,True,Very Low

In [95]:
whitewine_df[~(whitewine_df['fixed_acidity_bins'] == 'Very High')]  #['fixed_acidity_bins'].unique()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alcohol_above_avg,fixed_acidity_bins
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6,False,Low
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6,False,Low
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6,False,Medium
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,False,Low
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,False,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,True,Low
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,False,Low
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,False,Low
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,True,Very Low
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,True,Low

## Task 5.

Let's say that I now want to know how much my decision to avoid those wines with higher `alcohol` content is going to limit the `quality` of wines that I can drink. To figure this out, I want to know a couple of things: 

 * The average `alcohol` content for those reds above the mean `alcohol` level, by quality.
 * The average `alcohol` content for those whites above the mean `alcohol` level, by quality. 
 
 Use a `pivot table` to solve this.

In [79]:
redwine_df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'alcohol_above_avg'],
      dtype='object')

In [84]:
redwine_df[redwine_df['alcohol_above_avg'] == True].groupby('quality').mean()['alcohol']

quality
3    10.866667
4    11.295000
5    11.088686
6    11.437214
7    11.708236
8    12.368750
Name: alcohol, dtype: float64

In [87]:
redwine_df[redwine_df['alcohol_above_avg'] == True].pivot_table(index='quality', values='alcohol', aggfunc='mean')

           alcohol
quality
3        10.866667
4        11.295000
5        11.088686
6        11.437214
7        11.708236
8        12.368750

In [88]:
redwine_df[redwine_df['alcohol_above_avg'] == True].pivot_table(index='quality', values=['alcohol', 'residual sugar'], aggfunc=['mean', 'min', 'max'])

              mean                    min                    max  \
           alcohol residual sugar alcohol residual sugar alcohol
quality
3        10.866667       3.250000    10.7            2.1    11.0
4        11.295000       3.545000    10.5            1.4    13.1
5        11.088686       2.776642    10.5            1.5    14.9
6        11.437214       2.464328    10.5            0.9    14.0
7        11.708236       2.755814    10.5            1.2    14.0
8        12.368750       2.656250    11.0            1.4    14.0


        residual sugar
quality
3                 4.25
4                12.90
5                 7.80
6                13.90
7                 8.90
8                 6.40

## Task 6.

Now, do the same for my decision to avoid wines with a high acidity next month: 

 * Find the average `alcohol` content for reds, by `quality` and `fixed acidity` bin. 
 * Find the average `alcohol` content for whites, by `quality` and `fixed acidity` bin. 
 
  Use a `pivot table` to solve this.

In [93]:
redwine_df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'alcohol_above_avg'],
      dtype='object')

In [106]:
redwine_df.pivot_table(index=['quality', 'fixed_acidity_bins'], values='alcohol', aggfunc='mean', observed=False)

                              alcohol
quality fixed_acidity_bins
3       Very Low             9.875000
        Low                 10.500000
        Medium               9.150000
        High                 9.000000
4       Very Low            11.006667
        Low                  9.981667
        Medium               9.920000
        High                 9.966667
5       Very Low            10.304245
        Low                  9.773727
        Medium               9.846429
        High                10.229630
        Very High           12.050000
6       Very Low            11.223529
        Low                 10.431985
        Medium              10.687395
        High                10.480952
        Very High           10.240000
7       Very Low            12.195402
        Low                 11.486413
        Medium              11.383333
        High                10.809524
        Very High            9.866667
8       Very Low            13.633333
        Low                 11.937500
        Medium              11.916667
        High                 9.800000

In [107]:
whitewine_df.pivot_table(index=['quality', 'fixed_acidity_bins'], values='alcohol', aggfunc='mean', observed=False)

                              alcohol
quality fixed_acidity_bins
3       Very Low             9.850000
        Low                 10.472727
        Medium              10.540000
        High                 9.650000
4       Very Low            10.786364
        Low                 10.102564
        Medium              10.126471
        High                 9.900000
5       Very Low            10.136635
        Low                  9.732173
        Medium              10.176452
        High                 9.700000
6       Very Low            10.902765
        Low                 10.529056
        Medium              10.635247
        High                 9.500000
        Very High           11.100000
7       Very Low            12.021405
        Low                 11.303724
        Medium              10.988679
8       Very Low            12.403030
        Low                 11.486364
        Medium              11.080000
9       Low                 12.625000
        Medium              10.400000